#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent

request = json.load(sys.stdin)

agent.set_env('LOKI_RETENTION_PERIOD', f"{request['retention_days']}")
