#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent

agent.unset_env('SYSLOG_IP')
agent.unset_env('SYSLOG_PORT')
agent.unset_env('SYSLOG_PROTOCOL')
agent.unset_env('SYSLOG_FORMAT')