#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import os

def genuuid():
    uuid =  os.popen("uuidgen")
    return uuid.read()

node_id = os.environ['NODE_ID']
port = os.environ['TCP_PORT']

rdb = agent.redis_connect()
rkey = f'node/{node_id}/vpn'
ip_address = rdb.hget(rkey, 'ip_address')

agent.set_env('LOKI_ADDR', ip_address)
agent.set_env('LOKI_API_AUTH_USERNAME', 'loki')
agent.set_env('LOKI_API_AUTH_PASSWORD', genuuid())
agent.set_env('LOKI_LOGS_INGRESS_TOKEN', genuuid())
agent.set_env('LOKI_HTTP_PORT', port)
