#!/usr/bin/env sh

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

read -r active < <(jq -r '[.active] | join("\t")')

systemctl --user disable --now syslog-forwarder.service

if $active; then
    systemctl --user enable --now syslog-forwarder.service
fi
