#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import os
import json
import sys

response = {
    "retention_days": int(os.getenv('LOKI_RETENTION_PERIOD')),
    "active_from": os.getenv('LOKI_ACTIVE_FROM')
}

if os.getenv('LOKI_ACTIVE_TO') is not None:
    response['active_to'] = os.getenv('LOKI_ACTIVE_TO')

json.dump(response, sys.stdout)
