#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import datetime

import agent

# Check if event comes from the cluster
if os.getenv("AGENT_EVENT_SOURCE") == 'cluster':
    # parse data
    data = json.load(sys.stdin)
    if 'instance' in data and data['instance'] == 'loki':
        if 'previous' in data and data['previous'] == os.getenv('MODULE_ID') and os.getenv('LOKI_ACTIVE_TO') is None:
            agent.set_env('LOKI_ACTIVE_TO', datetime.datetime.now().astimezone().isoformat())
