#!/usr/bin/env python3

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent
import os

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
        "LOKI_RETENTION_PERIOD",
        "LOKI_ACTIVE_FROM",
        # NOTE: LOKI_ACTIVE_TO is restored by a later step
    ]:
    agent.set_env(evar, original_environment[evar])
